fragment OrganizationListItem on OrganizationDto {
  childCount
  children {
    ...Organization
  }
  languages
  level
  name
  organizationId
  parent {
    ...Organization
  }
  parentId
}

fragment Organization on OrganizationDto {
  childCount
  languages
  level
  name
  organizationId
  parentId
}