fragment UserRoleDetail on RoleDetailsDto  {
  canBeSet
  isEnabled
  role
}


fragment UserRole on KeyValuePairOfOrganizationLevelAndListOfRoleDetailsDto  {
  key
  value {
    ...UserRoleDetail
  }
}

fragment UserListItem on UserDto {
  createdAt
  email
  firstName
  isEnabled
  lastName
  organizationId
  roles {
    ...UserRole
  }
  updatedAt
  userId
}